'''This module consists of callbacks that
are generated by inline keyboard buttons.'''


from typing import Optional

from aiogram.filters.callback_data import CallbackData


class MoveCellCallback(
    CallbackData,
    prefix = 'move'
):
    value: str
    

class ReadyCallback(
    CallbackData,
    prefix = 'ready'
):
    value: Optional[str]
    
    
class ExitCallback(
    CallbackData,
    prefix = 'exit'
):
    value: Optional[str]
    
